require 'text/double_metaphone'
require 'text/figlet'
require 'text/levenshtein'
require 'text/metaphone'
require 'text/porter_stemming'
require 'text/soundex'
require 'text/version'
require 'text/white_similarity'
